version: "2.1"

networks:
  test:

services:
  api:
    image: api:1.0
    build: .
    networks:
      - test
    extra_hosts:
      - "peer0.org1.example.com:34.125.51.62"
      - "peer0.org2.example.com:34.125.115.109"
      - "peer0.org3.example.com:34.125.145.115"
      - "peer1.org1.example.com:34.125.51.62"
      - "peer2.org2.example.com:34.125.115.109"
      - "peer3.org3.example.com:34.125.145.115"
      - "orderer.example.com:34.16.131.165"
      - "orderer2.example.com:34.16.131.165"
      - "orderer3.example.com:34.16.131.165"
    ports:
      - 4000:4000
